language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database koffietime;' -U postgres
  - psql -c "CREATE USER koffie;" -U postgres
  - psql -c "ALTER USER koffie CREATEDB;"

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source='koffietime/apps' manage.py test && coverage report

after_success:
  - coveralls
