# Generated by Django 2.2.8 on 2019-12-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarked',
        ),
    ]
